export const categories = [
    {
        slug: "entradas-sopas",
        namePt: "Entradas & Sopas",
        nameEn: "Starters & Soups",
        nameEs: "Entradas & Sopas",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/soup.svg",
        bannerUrl: "/banners/starters-soups.png",
        sortOrder: 1,
    },
    {
        slug: "saladas",
        namePt: "Saladas",
        nameEn: "Salads",
        nameEs: "Ensaladas",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/salad.svg",
        bannerUrl: "/banners/salads.png",
        sortOrder: 2,
    },
    {
        slug: "sanduiches",
        namePt: "Sanduíches",
        nameEn: "Sandwiches",
        nameEs: "Sándwiches",
        descPt: "Todos acompanham fritas",
        descEn: "All served with fries",
        descEs: "Todos acompañados de papas fritas",
        iconUrl: "/icons/sandwich.svg",
        bannerUrl: "/banners/sandwiches.png",
        sortOrder: 3,
    },
    {
        slug: "pizzas",
        namePt: "Pizzas Individuais",
        nameEn: "Individual Pizzas",
        nameEs: "Pizzas Individuales",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/pizza.svg",
        bannerUrl: "/banners/pizzas.png",
        sortOrder: 4,
    },
    {
        slug: "massas-risotos",
        namePt: "Massas & Risotos",
        nameEn: "Pasta & Risottos",
        nameEs: "Pastas & Risottos",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/pasta.svg",
        bannerUrl: "/banners/pasta-risotto.png",
        sortOrder: 5,
    },
    {
        slug: "pratos-principais",
        namePt: "Pratos Principais",
        nameEn: "Main Courses",
        nameEs: "Platos Principales",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/main-dish.svg",
        bannerUrl: "/banners/main-courses.png",
        sortOrder: 6,
    },
    {
        slug: "sobremesas",
        namePt: "Sobremesas",
        nameEn: "Desserts",
        nameEs: "Postres",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/dessert.svg",
        bannerUrl: "/banners/desserts.png",
        sortOrder: 7,
    },
    {
        slug: "cafes-chas-chocolates",
        namePt: "Cafés, Chás e Chocolates",
        nameEn: "Coffee, Tea & Chocolate",
        nameEs: "Cafés, Tés y Chocolates",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/coffee.svg",
        bannerUrl: "/banners/coffee-tea-chocolate.png",
        sortOrder: 8,
    },
    {
        slug: "aguas-refri-sucos",
        namePt: "Águas, Refrigerantes e Sucos",
        nameEn: "Water, Soft Drinks & Juices",
        nameEs: "Aguas, Refrescos y Jugos",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/water.svg",
        bannerUrl: "/banners/water-softdrinks-juices.png",
        sortOrder: 9,
    },
    {
        slug: "cervejas",
        namePt: "Cervejas",
        nameEn: "Beers",
        nameEs: "Cervezas",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/beer.svg",
        bannerUrl: "/banners/beers.png",
        sortOrder: 10,
    },
    {
        slug: "coqueteis",
        namePt: "Coquetéis",
        nameEn: "Cocktails",
        nameEs: "Cócteles",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/cocktail.svg",
        bannerUrl: "/banners/cocktails.png",
        sortOrder: 11,
    },
    {
        slug: "aperitivos-destilados",
        namePt: "Aperitivos & Destilados",
        nameEn: "Aperitifs & Spirits",
        nameEs: "Aperitivos & Destilados",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/wine.svg",
        bannerUrl: "/banners/spirits-aperitifs.png",
        sortOrder: 12,
    },
    {
        slug: "whisky",
        namePt: "Whisky",
        nameEn: "Whisky",
        nameEs: "Whisky",
        descPt: null,
        descEn: null,
        descEs: null,
        iconUrl: "/icons/whisky.svg",
        bannerUrl: "/banners/whisky.png",
        sortOrder: 13,
    },
    {
        slug: "vinhos",
        namePt: "Vinhos",
        nameEn: "Wines",
        nameEs: "Vinos",
        descPt: "Carta de vinhos",
        descEn: "Wine list",
        descEs: "Carta de vinos",
        iconUrl: "/icons/wine.svg",
        bannerUrl: "/banners/wines.png",
        sortOrder: 14,
    },
];