export const subCategories = [
    {
        catSlug: "vinhos",
        slug: "argentina",
        namePt: "Argentina",
        nameEn: "Argentina",
        nameEs: "Argentina",
        sortOrder: 1,
    },
    {
        catSlug: "vinhos",
        slug: "chile",
        namePt: "Chile",
        nameEn: "Chile",
        nameEs: "Chile",
        sortOrder: 2,
    },
    {
        catSlug: "vinhos",
        slug: "espanha",
        namePt: "Espanha",
        nameEn: "Spain",
        nameEs: "España",
        sortOrder: 3,
    },
    {
        catSlug: "vinhos",
        slug: "franca",
        namePt: "França",
        nameEn: "France",
        nameEs: "Francia",
        sortOrder: 4,
    },
    {
        catSlug: "vinhos",
        slug: "portugal",
        namePt: "Portugal",
        nameEn: "Portugal",
        nameEs: "Portugal",
        sortOrder: 5,
    },
    {
        catSlug: "vinhos",
        slug: "brasil",
        namePt: "Brasil",
        nameEn: "Brazil",
        nameEs: "Brasil",
        sortOrder: 6,
    },
    {
        catSlug: "vinhos",
        slug: "italia",
        namePt: "Itália",
        nameEn: "Italy",
        nameEs: "Italia",
        sortOrder: 7,
    },
];